import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
export type Language = 'en' | 'rw' | 'fr';
const labels = { en: { dashboard:'Dashboard', patients:'Patients', appointments:'Appointments', referrals:'Referrals', doctors:'Doctors', hospitals:'Hospitals', laboratories:'Laboratories', consultations:'Consultations', settings:'Settings' }, rw: { dashboard:'Ibiro bikuru', patients:'Abarwayi', appointments:'Gahunda', referrals:'Iyohereza', doctors:'Abaganga', hospitals:'Ibitaro', laboratories:'Laboratwari', consultations:'Kwamamaza', settings:'Igenamiterere' }, fr: { dashboard:'Tableau de bord', patients:'Patients', appointments:'Rendez-vous', referrals:'Orientations', doctors:'Médecins', hospitals:'Hôpitaux', laboratories:'Laboratoires', consultations:'Consultations', settings:'Paramètres' } };
const C=createContext<{language:Language;setLanguage:(x:Language)=>void;t:(x:keyof typeof labels.en)=>string}|null>(null);
const phrases: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  rw: { 'Back to Dashboard':'Subira ku rupapuro rukuru', 'Add Patient':'Ongeramo umurwayi', 'New Appointment':'Teganya gahunda', 'New Referral':'Kora iyohereza', 'Patients':'Abarwayi', 'Appointments':'Gahunda', 'Referrals':'Iyohereza', 'Doctors':'Abaganga', 'Hospitals & Clinics':'Ibitaro n’amavuriro', 'Laboratories':'Laboratwari', 'Settings':'Igenamiterere', 'Save':'Bika', 'Cancel':'Hagarika', 'Delete':'Siba', 'Edit':'Hindura', 'Create':'Kora', 'Search patients, appointments...':'Shakisha abarwayi cyangwa gahunda...', 'No appointments scheduled':'Nta gahunda zateganyijwe', 'No lab tests yet':'Nta bipimo bya laboratwari biraboneka', 'Loading medical record…':'Kwamamaza inyandiko z’ubuvuzi…', 'Export record':'Ohereza inyandiko', 'Medical history':'Amateka y’uburwayi', 'Allergies':'Ibintu byangiza umubiri', 'Prescriptions':'Imiti yanditswe', 'Clinical visits':'Isuzuma ry’abarwayi', 'Referral consultations':'Kwamamaza ku iyohereza', 'Privacy & compliance':'Ubuzima bwite n’amabwiriza' },
  fr: { 'Back to Dashboard':'Retour au tableau de bord', 'Add Patient':'Ajouter un patient', 'New Appointment':'Nouveau rendez-vous', 'New Referral':'Nouvelle orientation', 'Patients':'Patients', 'Appointments':'Rendez-vous', 'Referrals':'Orientations', 'Doctors':'Médecins', 'Hospitals & Clinics':'Hôpitaux et cliniques', 'Laboratories':'Laboratoires', 'Settings':'Paramètres', 'Save':'Enregistrer', 'Cancel':'Annuler', 'Delete':'Supprimer', 'Edit':'Modifier', 'Create':'Créer', 'Search patients, appointments...':'Rechercher des patients ou rendez-vous...', 'No appointments scheduled':'Aucun rendez-vous programmé', 'No lab tests yet':'Aucun examen de laboratoire', 'Loading medical record…':'Chargement du dossier médical…', 'Export record':'Exporter le dossier', 'Medical history':'Antécédents médicaux', 'Allergies':'Allergies', 'Prescriptions':'Ordonnances', 'Clinical visits':'Consultations cliniques', 'Referral consultations':'Consultations d’orientation', 'Privacy & compliance':'Confidentialité et conformité' }
};
function LiveTranslator({ language }: { language: Language }) { const originals = useRef(new WeakMap<Text, string>()); useEffect(() => { const dictionary = language === 'en' ? {} : phrases[language]; const translate = () => { const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let node: Text | null; while ((node = walker.nextNode() as Text | null)) { const text = node.nodeValue || ''; const source = originals.current.get(node) || text; originals.current.set(node, source); const translated = dictionary[source.trim()] || source.trim(); if (translated !== text.trim()) node.nodeValue = text.replace(text.trim(), translated); } document.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>('[placeholder]').forEach(el => { const source = el.dataset.sympraPlaceholder || el.placeholder; el.dataset.sympraPlaceholder = source; el.placeholder = dictionary[source] || source; }); }; translate(); const observer = new MutationObserver(translate); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, [language]); return null; }
export const LanguageProvider=({children}:{children:ReactNode})=>{const[language,setLanguageState]=useState<Language>(()=>(localStorage.getItem('sympra_language') as Language)||'en');const setLanguage=(x:Language)=>{localStorage.setItem('sympra_language',x);document.documentElement.lang=x;setLanguageState(x)};return <C.Provider value={{language,setLanguage,t:k=>labels[language][k]}}><LiveTranslator language={language}/>{children}</C.Provider>}; export const useLanguage=()=>{const v=useContext(C);if(!v)throw new Error('Language provider missing');return v};
