import { useEffect, useState } from 'react';
import { ArrowLeft, Download, FilePlus, Plus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import Modal from '../components/Modal';
import { api } from '../services/api';
import type { Patient, Visit } from '../Types';

export default function MedicalRecords() {
  const { id = '' } = useParams(); const [patient, setPatient] = useState<Patient | null>(null); const [visits, setVisits] = useState<Visit[]>([]); const [modal, setModal] = useState<'history'|'allergy'|'prescription'|'attachment'|null>(null); const [error, setError] = useState('');
  const load = async () => { const [p, v] = await Promise.all([api.getPatient(id), api.getVisits(id)]); setPatient(p); setVisits(v); };
  useEffect(() => { load().catch(e => setError(e.message)); }, [id]);
  const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!modal) return; const form = new FormData(e.currentTarget); const data = Object.fromEntries(form); try { if (modal === 'history') await api.addMedicalHistory(id, data); if (modal === 'allergy') await api.addAllergy(id, data); if (modal === 'prescription') await api.addPrescription(id, data); if (modal === 'attachment') { const file = form.get('file') as File; if (file?.size) { if (file.size > 2 * 1024 * 1024) throw new Error('Attachments must be 2 MB or smaller'); if (!['application/pdf', 'image/jpeg', 'image/png'].includes(file.type)) throw new Error('Use a PDF, PNG, or JPG attachment'); data.name = file.name; data.mimeType = file.type; data.url = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('Unable to read attachment')); reader.readAsDataURL(file); }); } await api.addAttachment(id, data); } setModal(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save record'); } };
  const exportRecord = async () => { const data = await api.exportPatient(id); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${patient?.name || 'patient'}-record.json`; a.click(); URL.revokeObjectURL(url); };
  if (!patient) return <p>{error || 'Loading medical record…'}</p>;
  const action = (name: typeof modal, label: string) => <button className="btn-secondary btn-sm" onClick={() => setModal(name)}><Plus size={14}/>{label}</button>;
  return <><div className="page-header"><div><Link to="/patients" className="back-link-header"><ArrowLeft size={16}/> Patients</Link><h1>{patient.name}</h1><p>Longitudinal medical record</p></div><button className="btn-secondary" onClick={exportRecord}><Download size={16}/> Export record</button></div>
  <div className="dashboard-grid"><div className="dashboard-main"><section className="panel"><div className="panel-header"><h2>Clinical visits</h2></div>{visits.length ? visits.map(v => <article className="result-card" key={v.id}><div><strong>{v.diagnosis || 'Clinical examination'}</strong><p>{v.chiefComplaint}</p></div><small>{new Date(v.visitedAt).toLocaleDateString()} · {v.clinicianName}</small></article>) : <p className="empty-cell">No visits recorded.</p>}</section><section className="panel"><div className="panel-header"><h2>Medical history</h2>{action('history', 'Add')}</div>{patient.medicalHistory?.map((x, i) => <p key={i}><strong>{x.condition}</strong> — {x.notes}</p>) || <p>No history added.</p>}</section><section className="panel"><div className="panel-header"><h2>Prescriptions</h2>{action('prescription', 'Add')}</div>{patient.prescriptions?.map((x, i) => <p key={i}><strong>{x.medication}</strong> {x.dosage} — {x.instructions}</p>) || <p>No prescriptions added.</p>}</section></div><aside className="dashboard-side"><section className="panel"><div className="panel-header"><h2>Allergies</h2>{action('allergy', 'Add')}</div>{patient.allergies?.map((x, i) => <p key={i}><strong>{x.substance}</strong><br/><small>{x.reaction} {x.severity && `(${x.severity})`}</small></p>) || <p>No known allergies recorded.</p>}</section><section className="panel"><div className="panel-header"><h2>Attachments</h2>{action('attachment', 'Add')}</div>{patient.attachments?.map((x, i) => <p key={i}><FilePlus size={14}/> <a href={x.url} target="_blank">{x.name}</a></p>) || <p>No attachments.</p>}</section></aside></div>
  <Modal title={`Add ${modal || ''}`} open={!!modal} onClose={() => setModal(null)}><form className="form-grid" onSubmit={save}>{modal === 'history' && <><label>Condition *<input name="condition" required/></label><label>Diagnosed on<input type="date" name="diagnosedOn"/></label><label className="full-width">Notes<textarea name="notes" rows={3}/></label></>}{modal === 'allergy' && <><label>Substance *<input name="substance" required/></label><label>Reaction<input name="reaction"/></label><label>Severity<select name="severity"><option>Low</option><option>Moderate</option><option>Severe</option></select></label></>}{modal === 'prescription' && <><label>Medication *<input name="medication" required/></label><label>Dosage<input name="dosage"/></label><label className="full-width">Instructions<textarea name="instructions" rows={3}/></label></>}{modal === 'attachment' && <><label className="full-width">PDF, PNG, or JPG (max 2 MB)<input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/></label></>}<button className="btn-primary full-width">Save record</button></form></Modal></>;
}
